### ISSUE TITLE
rich text paragraph block, position and shape bullet points

### ISSUE THREAD

**Issue by maxliqd** [liqd/digitalstrategie#494]
**URL:** https://gd-stage.liqd.net/data-governance/
**user:** visitor
**expected behaviour:** Bullet point lists are indented
**behaviour:** Bullet point are cut off in the middle and not indented
**important screensize:** Desktop, mobile
**device & browser:** mac, chrome, safari (bullet points not cut off on Firefox)
**Comment/Question:** 
Related to styleguide update?

Screenshot?
Desktop Chrome
![image](https://user-images.githubusercontent.com/94360651/189679823-37d45469-524b-4b3e-a165-b021a7912b76.png)
![image](https://user-images.githubusercontent.com/94360651/189679895-e77ec141-849d-4121-876a-1d15a34ff6da.png)

Mobile Chrome
![image](https://user-images.githubusercontent.com/94360651/189680150-f832c7a7-924e-41fd-bb39-666aa923440c.png)

**Comment by maxliqd** [comment]
@mcastro-lqd Is the list indented enough?

**Comment by phillimorland** [comment]
NOTE: bullet point crop is mac issue, works in ff and chrome on linux.
@maxliqd @mcastro-lqd would you both be able to check to see if this issue is still present and if so add you versions of safari to the issue? thank you!

**Comment by maxliqd** [comment]
Still present on mac in safari:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/94360651/199212470-c226442e-8235-4d56-a069-5a6614ecbf93.png">

**Comment by maxliqd** [comment]
It is ok in chrome and firefox on mac

**Comment by mcastro-lqd** [comment]
Same here @maxliqd

**Comment by maxliqd** [comment]
Dev on safari, chrome and firefox is fine.

**Comment by maxliqd** [comment]
Bullet points are cut off on stage again: https://gd-stage.liqd.net/de/strategie/massnahmen/zentrale-ma%C3%9Fnahmen/

Could it be related to the font update?

**Comment by maxliqd** [comment]
![image](https://user-images.githubusercontent.com/94360651/201885094-fc400a30-a3ac-42d8-8eef-fb8a3019903e.png)

**Comment by fuzzylogic2000** [comment]
@maxliqd This should be fixed on dev now. Could you check and let us know when it's good to go on stage and prod?

**Comment by maxliqd** [comment]
It looks ok on dev in block paragraph: https://gd-dev.liqd.net/de/test-video-block/ 
![image](https://user-images.githubusercontent.com/94360651/201901054-23ee3e7f-a0dc-4cab-b3e0-b8c68c268d1f.png)

And in the overview page intro text: https://gd-dev.liqd.net/de/ergebnisse/
![image](https://user-images.githubusercontent.com/94360651/201901327-c9ee0b2b-3cad-46cd-a039-10d6d152e0dd.png)

**Comment by maxliqd** [comment]
This issue is back on dev and stage on chrome (Version 113.0.5672.126 (Offizieller Build) (arm64)) and safari (Version 16.2 (18614.3.7.1.5)), macOS Ventura 13.1. Not on firefox though.

https://gd-stage.liqd.net/de/das-ist-gemeinsam-digital-berlin/team-der-digitalstrategie-showing-problems-with-detail-page/

https://gd-dev.liqd.net/de/%C3%BCber-den-prozess-overview-page/team/

@philli-m I think we decided to add two tab spaces last time, right?
